### ISSUE TITLE
Support other delimiter than dot(.) like _

### ISSUE THREAD

**Issue by SWHes** [leptonyu/salak.rs#1]
Hi,

Setting an environment variable with a dot in it is sometimes impossible.
This thread illustrates the issue: https://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it

I think it would be nice to be able to configure the separator. Maybe in the builder?

I imagine you used the dot to be easily compliant with the rust variable that might contain underscore. This can be handled with `#[salak(name="...")]` and any string that does not contain the separator.

**Comment by SWHes** [comment]
I just did a few tests and found that underscore works. So maybe this issue should be more about documenting the complete behavior. Currently, the documentation states :
> - a.b.c is a normal key separated by dot(.).
> - a.b[0], a.b[1], a.b[2]… is a group of keys with arrays.

and I could not find any mention of the library supporting underscores.

**Comment by leptonyu** [comment]
Hi @SWHes, just saw the issue. 

I'm rewriting this crate, and will improve the documents as you requested.

A key is composed with sub keys  separated by dot(.), sub key can have index expression, and for it's raw part, sub key has pattern `[_a-zA-Z0-9]+`.

So a complete regex is `[_a-zA-Z0-9]+(\[[0-9]+\])*(\.[_a-zA-Z0-9]+(\[[0-9]+\])*)*`.


Thanks.

**Comment by leptonyu** [comment]
Hi @SWHes , I've published `v0.10.0`. I think document should ok now. So I will close this issue.
